[theme]
base="light"
primaryColor="slateBlue"
backgroundColor="mintCream"
secondaryBackgroundColor="darkSeaGreen"
baseRadius="full"
font = "Stardos Stencil:https://fonts.googleapis.com/css2?family=Stardos+Stencil:wght@400;700&display=swap, sans-serif"
baseFontSize = 19

[runner]
magicEnabled = false
